"""
Tests for Kruskal MST implementation and parity against Borůvka.

Coverage:
  - Correctness on a small graph with known MST
  - Exact MST-weight parity between Kruskal and Borůvka on precomputed graphs
  - HDBSCAN cluster-label parity (Kruskal vs Borůvka) on feature matrices
  - Disconnected and edge-case graphs (isolated nodes, single edge, etc.)
  - HDBSCAN API: algorithm='kruskal' with both metric='euclidean' and
    metric='precomputed'
  - compute_minimum_spanning_tree bad-algorithm guard
  
Tested generated by Claude Sonnet and Opus 4.6. Manual review and editing by Richard Hakim 2026_03_05.
"""

import numpy as np
import pytest
from scipy import sparse
from scipy.spatial import distance
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler
from sklearn.utils import shuffle

from fast_hdbscan import HDBSCAN, fast_hdbscan
from fast_hdbscan.hdbscan import compute_minimum_spanning_tree


# ---------------------------------------------------------------------------
# Shared helpers / datasets
# ---------------------------------------------------------------------------

def _make_connected_sparse_graph(n=12, seed=7):
    """Chain + random extra edges — always connected."""
    rng = np.random.RandomState(seed)
    rows, cols, data = [], [], []
    for i in range(n - 1):
        w = rng.uniform(0.1, 1.0)
        rows += [i, i + 1]
        cols += [i + 1, i]
        data += [w, w]
    for _ in range(n):
        i, j = rng.choice(n, 2, replace=False)
        w = rng.uniform(0.1, 2.0)
        rows += [i, j]
        cols += [j, i]
        data += [w, w]
    return sparse.csr_matrix((data, (rows, cols)), shape=(n, n), dtype=np.float64)


def _full_pairwise_sparse(X):
    """Complete pairwise Euclidean distance CSR from float32-cast feature matrix."""
    X32 = X.astype(np.float32)
    D = distance.cdist(X32, X32)
    np.fill_diagonal(D, 0.0)
    return sparse.csr_matrix(D)


def _align_labels(ref, other):
    mapping = {}
    for r, o in zip(ref, other):
        if r == -1 or o == -1:
            continue
        mapping.setdefault(o, []).append(r)
    remap = {o: max(set(vs), key=vs.count) for o, vs in mapping.items()}
    return np.array([remap.get(v, v) for v in other])


# Module-level datasets (computed once)
_X_blobs, _ = make_blobs(
    n_samples=60,
    centers=[[-4, -4], [0, 0], [4, 4]],
    cluster_std=0.3,
    random_state=0,
)
_X_blobs = StandardScaler().fit_transform(_X_blobs)

from sklearn import datasets as _sk_datasets
_X_moons, _ = _sk_datasets.make_moons(n_samples=100, noise=0.05, random_state=0)
_X_moons = StandardScaler().fit_transform(_X_moons)

_G_blobs = _full_pairwise_sparse(_X_blobs)
_G_moons = _full_pairwise_sparse(_X_moons)


# ---------------------------------------------------------------------------
# 1. Kruskal JIT correctness on a tiny known graph
# ---------------------------------------------------------------------------

def test_kruskal_known_triangle():
    """
    3-node complete graph.  Edges: 0-1 w=1, 1-2 w=2, 0-2 w=3.
    MST must contain 0-1 (w=1) and 1-2 (w=2).  Total weight = 3.
    """
    rows = [0, 1, 1, 2, 0, 2]
    cols = [1, 0, 2, 1, 2, 0]
    data = [1.0, 1.0, 2.0, 2.0, 3.0, 3.0]
    G = sparse.csr_matrix((data, (rows, cols)), shape=(3, 3), dtype=np.float64)

    mst, _, core_dists = compute_minimum_spanning_tree(
        G, min_samples=1, metric="precomputed", algorithm="kruskal"
    )
    assert mst.shape == (2, 3), "MST must have n-1=2 edges"
    assert np.isclose(np.sort(mst[:, 2]).sum(), 3.0), "Total MST weight must equal 3"


def test_kruskal_known_line_graph():
    """
    4-node path  0-1-2-3 with weights 4, 1, 3.
    MST == the path itself (no cycles).  min_samples=1 → cd=0 → MRD=edge weight.
    """
    rows = [0, 1, 1, 2, 2, 3]
    cols = [1, 0, 2, 1, 3, 2]
    data = [4.0, 4.0, 1.0, 1.0, 3.0, 3.0]
    G = sparse.csr_matrix((data, (rows, cols)), shape=(4, 4), dtype=np.float64)

    mst, _, _ = compute_minimum_spanning_tree(
        G, min_samples=1, metric="precomputed", algorithm="kruskal"
    )
    assert mst.shape == (3, 3)
    assert np.isclose(np.sort(mst[:, 2]).sum(), 1 + 3 + 4)


# ---------------------------------------------------------------------------
# 2. MST edge-count invariant
# ---------------------------------------------------------------------------

def test_kruskal_precomputed_edge_count():
    G = _make_connected_sparse_graph(n=15, seed=99)
    mst, neighbors, core_dists = compute_minimum_spanning_tree(
        G, min_samples=3, metric="precomputed", algorithm="kruskal"
    )
    assert mst.shape == (14, 3), "MST must have n-1=14 edges for n=15"
    assert neighbors.shape[0] == 15
    assert core_dists.shape == (15,)


def test_kruskal_feature_matrix_edge_count():
    mst, neighbors, core_dists = compute_minimum_spanning_tree(
        _X_blobs, min_samples=5, metric="euclidean", algorithm="kruskal",
        knn_k=10,
    )
    n = _X_blobs.shape[0]
    assert mst.shape == (n - 1, 3), f"Expected {n - 1} MST edges, got {mst.shape[0]}"
    assert neighbors.shape[0] == n
    assert core_dists.shape == (n,)


# ---------------------------------------------------------------------------
# 3. Kruskal vs Borůvka MST weight parity on precomputed sparse graphs
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("min_samples", [1, 3, 5])
def test_kruskal_boruvka_precomputed_mst_weights(min_samples):
    """
    Kruskal and Borůvka, given the same precomputed graph, must produce
    identical MST edge-weight multisets.

    Kruskal works entirely in float64; Borůvka uses float32 internally but
    patches weights back to float64 afterwards.  On a full pairwise distance
    graph (no float32 precision gap) the resulting sorted weights must be
    bit-for-bit equal.
    """
    G = _G_blobs

    mst_k, _, cd_k = compute_minimum_spanning_tree(
        G, min_samples=min_samples, metric="precomputed", algorithm="kruskal"
    )
    mst_b, _, cd_b = compute_minimum_spanning_tree(
        G, min_samples=min_samples, metric="precomputed", algorithm="boruvka"
    )

    assert mst_k.shape == mst_b.shape, "MST sizes must match"
    np.testing.assert_array_equal(
        np.sort(mst_k[:, 2]),
        np.sort(mst_b[:, 2]),
        err_msg=(
            f"Kruskal vs Borůvka sorted MST weights differ "
            f"(min_samples={min_samples})"
        ),
    )
    np.testing.assert_array_equal(cd_k, cd_b, err_msg="Core distances must match")


# ---------------------------------------------------------------------------
# 4. Disconnected and degenerate graphs
# ---------------------------------------------------------------------------

def test_kruskal_disconnected_two_components():
    """Two isolated cliques → exactly one +inf bridge edge."""
    rows = [0, 1, 1, 2, 3, 4]
    cols = [1, 0, 2, 1, 4, 3]
    data = [1.0] * 6
    G = sparse.csr_matrix((data, (rows, cols)), shape=(5, 5), dtype=np.float64)

    mst, _, _ = compute_minimum_spanning_tree(
        G, min_samples=1, metric="precomputed", algorithm="kruskal"
    )
    assert mst.shape == (4, 3), "MST must have n-1=4 edges"
    inf_count = int(np.sum(np.isinf(mst[:, 2])))
    assert inf_count == 1, f"Expected 1 inf bridge edge, got {inf_count}"


def test_kruskal_fully_isolated_nodes():
    """Empty graph: all n-1 MST edges must be +inf bridges."""
    n = 6
    G = sparse.csr_matrix((n, n), dtype=np.float64)
    mst, _, _ = compute_minimum_spanning_tree(
        G, min_samples=1, metric="precomputed", algorithm="kruskal"
    )
    assert mst.shape == (n - 1, 3)
    assert np.all(np.isinf(mst[:, 2])), "All bridge edges must be +inf"


def test_kruskal_two_nodes():
    """Minimal graph: 2 nodes, 1 edge."""
    G = sparse.csr_matrix(
        ([1.5, 1.5], ([0, 1], [1, 0])), shape=(2, 2), dtype=np.float64
    )
    mst, _, _ = compute_minimum_spanning_tree(
        G, min_samples=1, metric="precomputed", algorithm="kruskal"
    )
    assert mst.shape == (1, 3)
    assert np.isclose(mst[0, 2], 1.5)


# ---------------------------------------------------------------------------
# 5. HDBSCAN cluster-label parity: Kruskal == Borůvka
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("dataset,X,G", [
    ("blobs", _X_blobs, _G_blobs),
    ("moons", _X_moons, _G_moons),
])
@pytest.mark.parametrize("min_samples", [1, 5])
def test_hdbscan_kruskal_boruvka_precomputed_label_parity(dataset, X, G, min_samples):
    """
    HDBSCAN with algorithm='kruskal' on precomputed graph must yield the same
    cluster assignments as algorithm='boruvka'.
    """
    k = HDBSCAN(
        min_cluster_size=10, min_samples=min_samples,
        metric="precomputed", algorithm="kruskal",
    ).fit(G)
    b = HDBSCAN(
        min_cluster_size=10, min_samples=min_samples,
        metric="precomputed", algorithm="boruvka",
    ).fit(G)

    k_n = len(set(k.labels_) - {-1})
    b_n = len(set(b.labels_) - {-1})
    assert k_n == b_n, (
        f"[{dataset} ms={min_samples}] cluster count: kruskal={k_n} boruvka={b_n}"
    )

    aligned = _align_labels(b.labels_, k.labels_)
    assert np.array_equal(b.labels_, aligned), (
        f"[{dataset} ms={min_samples}] label mismatch after alignment"
    )


@pytest.mark.parametrize("dataset,X", [
    ("blobs", _X_blobs),
    ("moons", _X_moons),
])
@pytest.mark.parametrize("min_samples", [1, 5])
def test_hdbscan_kruskal_boruvka_euclidean_label_parity(dataset, X, min_samples):
    """
    HDBSCAN with algorithm='kruskal' on feature matrix must yield the same
    cluster count as algorithm='boruvka'.  (Exact label equality is not
    guaranteed because Kruskal on KNN graph is an approximation of the full
    Borůvka MST, but for well-separated data they agree.)
    """
    k = HDBSCAN(
        min_cluster_size=10, min_samples=min_samples, algorithm="kruskal",
        knn_k=10,
    ).fit(X)
    b = HDBSCAN(
        min_cluster_size=10, min_samples=min_samples, algorithm="boruvka",
    ).fit(X)

    k_n = len(set(k.labels_) - {-1})
    b_n = len(set(b.labels_) - {-1})
    assert k_n == b_n, (
        f"[{dataset} ms={min_samples}] cluster count: kruskal={k_n} boruvka={b_n}"
    )


# ---------------------------------------------------------------------------
# 6. fast_hdbscan() function API with algorithm kwarg
# ---------------------------------------------------------------------------

def test_fast_hdbscan_kruskal_euclidean():
    labels, probs = fast_hdbscan(_X_blobs, min_cluster_size=10, algorithm="kruskal", knn_k=10)
    assert labels.shape == (_X_blobs.shape[0],)
    assert len(set(labels) - {-1}) >= 1


def test_fast_hdbscan_kruskal_precomputed():
    labels, probs = fast_hdbscan(
        _G_blobs, min_cluster_size=10, metric="precomputed", algorithm="kruskal"
    )
    assert labels.shape == (_G_blobs.shape[0],)
    n_clusters = len(set(labels) - {-1})
    assert n_clusters >= 1


# ---------------------------------------------------------------------------
# 7. Bad algorithm raises ValueError
# ---------------------------------------------------------------------------

def test_bad_algorithm_raises():
    with pytest.raises(ValueError, match="algorithm"):
        compute_minimum_spanning_tree(_X_blobs, algorithm="invalid_algo")


# ---------------------------------------------------------------------------
# 8. MST is a valid spanning tree (no self-loops, correct vertex range)
# ---------------------------------------------------------------------------

def _is_valid_spanning_tree(mst, n):
    """Check connectivity of non-inf MST edges using union-find."""
    finite = mst[~np.isinf(mst[:, 2])]
    # All vertex indices in range
    if len(finite) > 0:
        assert finite[:, :2].min() >= 0
        assert finite[:, :2].max() < n
    # No self-loops
    assert np.all(finite[:, 0] != finite[:, 1])


def test_kruskal_valid_spanning_tree_precomputed():
    G = _make_connected_sparse_graph(n=20, seed=42)
    mst, _, _ = compute_minimum_spanning_tree(
        G, min_samples=3, metric="precomputed", algorithm="kruskal"
    )
    _is_valid_spanning_tree(mst, 20)


def test_kruskal_valid_spanning_tree_euclidean():
    mst, _, _ = compute_minimum_spanning_tree(
        _X_blobs, min_samples=5, metric="euclidean", algorithm="kruskal",
        knn_k=10,
    )
    _is_valid_spanning_tree(mst, _X_blobs.shape[0])


# ---------------------------------------------------------------------------
# 9. Kruskal precomputed: explicit zero edges and asymmetric symmetrization
# ---------------------------------------------------------------------------

def test_kruskal_explicit_zero_edge_preserved():
    """Zero-weight edge must survive symmetrization and appear in MST."""
    rows = [0, 1, 1, 2, 2, 3]
    cols = [1, 0, 2, 1, 3, 2]
    data = [0.0, 0.0, 1.0, 1.0, 1.0, 1.0]
    G = sparse.csr_matrix((data, (rows, cols)), shape=(4, 4), dtype=np.float64)

    mst, _, _ = compute_minimum_spanning_tree(
        G, min_samples=1, metric="precomputed", algorithm="kruskal"
    )
    assert mst.shape == (3, 3)
    assert np.any(mst[:, 2] == 0.0), "Zero-weight edge must be in MST"


def test_kruskal_asymmetric_min_symmetrization():
    """Asymmetric weights symmetrized by min: edge (0,1) uses min(5,1)=1."""
    rows = [0, 1, 1, 2]
    cols = [1, 0, 2, 1]
    data = [5.0, 1.0, 2.0, 2.0]
    G = sparse.csr_matrix((data, (rows, cols)), shape=(3, 3), dtype=np.float64)

    mst, _, _ = compute_minimum_spanning_tree(
        G, min_samples=1, metric="precomputed", algorithm="kruskal"
    )
    edge_01 = mst[
        ((mst[:, 0] == 0) & (mst[:, 1] == 1))
        | ((mst[:, 0] == 1) & (mst[:, 1] == 0))
    ]
    assert len(edge_01) == 1
    assert np.isclose(edge_01[0, 2], 1.0), "Symmetrized edge weight must be 1.0"


# ---------------------------------------------------------------------------
# 10. Kruskal min_samples=1 (zero core distances) on feature matrix
# ---------------------------------------------------------------------------

def test_kruskal_feature_matrix_min_samples_1():
    mst, neighbors, core_dists = compute_minimum_spanning_tree(
        _X_blobs, min_samples=1, metric="euclidean", algorithm="kruskal",
        knn_k=10,
    )
    n = _X_blobs.shape[0]
    assert mst.shape == (n - 1, 3)
    assert np.all(core_dists == 0.0), "min_samples=1 -> zero core distances"


# ---------------------------------------------------------------------------
# 11. knn_k parameter: brute-force (knn_k=None) vs KNN (knn_k=int)
# ---------------------------------------------------------------------------

def test_kruskal_brute_edge_count():
    """knn_k=None (full pairwise) must produce exactly n-1 MST edges."""
    mst, neighbors, core_dists = compute_minimum_spanning_tree(
        _X_blobs, min_samples=5, metric="euclidean", algorithm="kruskal",
        knn_k=None,
    )
    n = _X_blobs.shape[0]
    assert mst.shape == (n - 1, 3)
    assert not np.any(np.isinf(mst[:, 2])), "Brute-force MST should have no inf edges"


def test_kruskal_brute_min_samples_1():
    """knn_k=None with min_samples=1 -> zero core distances, valid MST."""
    mst, neighbors, core_dists = compute_minimum_spanning_tree(
        _X_blobs, min_samples=1, metric="euclidean", algorithm="kruskal",
        knn_k=None,
    )
    n = _X_blobs.shape[0]
    assert mst.shape == (n - 1, 3)
    assert np.all(core_dists == 0.0)


@pytest.mark.parametrize("min_samples", [1, 5])
def test_kruskal_brute_vs_boruvka_mst_weights(min_samples):
    """
    Brute-force Kruskal (exact MST) and Boruvka (also exact) on the same
    feature data must produce identical sorted MST weight multisets.

    Small precision differences are possible because Boruvka works in
    float32 rdist internally while brute Kruskal uses cdist float64.
    We check approximate equality with tight tolerance.
    """
    mst_k, _, cd_k = compute_minimum_spanning_tree(
        _X_blobs, min_samples=min_samples, metric="euclidean",
        algorithm="kruskal", knn_k=None,
    )
    mst_b, _, cd_b = compute_minimum_spanning_tree(
        _X_blobs, min_samples=min_samples, metric="euclidean",
        algorithm="boruvka",
    )
    assert mst_k.shape == mst_b.shape
    np.testing.assert_allclose(
        np.sort(mst_k[:, 2]),
        np.sort(mst_b[:, 2]),
        rtol=1e-5,
        err_msg=f"Brute Kruskal vs Boruvka MST weights differ (ms={min_samples})",
    )


def test_kruskal_knn_explicit_k():
    """knn_k=<int> must produce valid MST with n-1 edges."""
    mst, neighbors, core_dists = compute_minimum_spanning_tree(
        _X_blobs, min_samples=5, metric="euclidean", algorithm="kruskal",
        knn_k=15,
    )
    n = _X_blobs.shape[0]
    assert mst.shape == (n - 1, 3)
    assert neighbors.shape[0] == n
    assert core_dists.shape == (n,)


def test_kruskal_knn_k_less_than_min_samples():
    """knn_k < min_samples should still work (k_query = max(knn_k, min_samples) + 1)."""
    mst, neighbors, core_dists = compute_minimum_spanning_tree(
        _X_blobs, min_samples=10, metric="euclidean", algorithm="kruskal",
        knn_k=3,
    )
    n = _X_blobs.shape[0]
    assert mst.shape == (n - 1, 3)


@pytest.mark.parametrize("min_samples", [1, 5])
def test_hdbscan_kruskal_brute_label_parity(min_samples):
    """HDBSCAN with knn_k=None (brute Kruskal) vs Boruvka on blobs."""
    k = HDBSCAN(
        min_cluster_size=10, min_samples=min_samples,
        algorithm="kruskal", knn_k=None,
    ).fit(_X_blobs)
    b = HDBSCAN(
        min_cluster_size=10, min_samples=min_samples,
        algorithm="boruvka",
    ).fit(_X_blobs)

    k_n = len(set(k.labels_) - {-1})
    b_n = len(set(b.labels_) - {-1})
    assert k_n == b_n, f"cluster count: kruskal_brute={k_n} boruvka={b_n}"


def test_hdbscan_kruskal_knn_k_explicit():
    """HDBSCAN with explicit knn_k threads through correctly."""
    h = HDBSCAN(
        min_cluster_size=10, min_samples=5, algorithm="kruskal", knn_k=20,
    ).fit(_X_blobs)
    assert h.labels_.shape == (_X_blobs.shape[0],)
    assert len(set(h.labels_) - {-1}) >= 1


def test_fast_hdbscan_knn_k_param():
    """fast_hdbscan() accepts knn_k parameter."""
    labels, probs = fast_hdbscan(
        _X_blobs, min_cluster_size=10, algorithm="kruskal", knn_k=15,
    )
    assert labels.shape == (_X_blobs.shape[0],)
    assert len(set(labels) - {-1}) >= 1


# ---------------------------------------------------------------------------
# Cannot-link constrained Kruskal tests
# ---------------------------------------------------------------------------

def _make_cl_matrix(n, pairs):
    """Build a sparse CL matrix from a list of (i, j) pairs (upper-tri only)."""
    if not pairs:
        return sparse.csr_matrix((n, n), dtype=np.int8)
    rows, cols = zip(*pairs)
    data = np.ones(len(pairs), dtype=np.int8)
    return sparse.csr_matrix((data, (rows, cols)), shape=(n, n))


class TestCannotLinkCore:
    """Tests for _kruskal_core_constrained JIT function."""

    def test_basic_cl_prevents_merge(self):
        """CL(0, 2) on a 3-node path: 0--1--2.  Must produce 2 components."""
        from fast_hdbscan.kruskal import (
            _kruskal_core_constrained, _validate_cannot_link,
        )
        # Path graph: 0-1 (w=1), 1-2 (w=2)
        weights = np.array([1.0, 2.0], dtype=np.float64)
        row_idx = np.array([0, 1], dtype=np.int32)
        col_idx = np.array([1, 2], dtype=np.int32)
        sorted_order = np.array([0, 1], dtype=np.int32)

        cl = _make_cl_matrix(3, [(0, 2)])
        cl_indices, cl_indptr = _validate_cannot_link(cl, 3)

        mst_edges, preds = _kruskal_core_constrained(
            weights, row_idx, col_idx, sorted_order, 3, cl_indices, cl_indptr
        )
        # Edge 0-1 accepted; edge 1-2 would merge {0,1} with {2},
        # but CL(0,2) forbids it.
        assert mst_edges.shape[0] == 1
        assert mst_edges[0, 0] == 0 and mst_edges[0, 1] == 1

    def test_cl_no_constraints_matches_unconstrained(self):
        """Empty CL matrix gives same result as unconstrained Kruskal."""
        from fast_hdbscan.kruskal import (
            _kruskal_core, _kruskal_core_constrained, _validate_cannot_link,
        )
        rng = np.random.RandomState(42)
        n = 8
        # Random complete graph (upper-triangle)
        tri_r, tri_c = np.triu_indices(n, k=1)
        weights = rng.uniform(0.1, 5.0, size=len(tri_r)).astype(np.float64)
        tri_r = tri_r.astype(np.int32)
        tri_c = tri_c.astype(np.int32)
        so = np.argsort(weights, kind="stable").astype(np.int32)

        cl = _make_cl_matrix(n, [])
        cl_i, cl_p = _validate_cannot_link(cl, n)

        mst_u, _ = _kruskal_core(weights, tri_r, tri_c, so, n)
        mst_c, _ = _kruskal_core_constrained(
            weights, tri_r, tri_c, so, n, cl_i, cl_p
        )
        np.testing.assert_array_equal(mst_u, mst_c)

    def test_cl_transitive_conflict(self):
        """CL(0, 3): merging {0,1,2} with {3} is blocked even though
        edge 2-3 doesn't directly involve vertex 0."""
        from fast_hdbscan.kruskal import (
            _kruskal_core_constrained, _validate_cannot_link,
        )
        # Edges: 0-1(1), 1-2(2), 2-3(3)
        weights = np.array([1.0, 2.0, 3.0], dtype=np.float64)
        row_idx = np.array([0, 1, 2], dtype=np.int32)
        col_idx = np.array([1, 2, 3], dtype=np.int32)
        so = np.array([0, 1, 2], dtype=np.int32)

        cl = _make_cl_matrix(4, [(0, 3)])
        cl_i, cl_p = _validate_cannot_link(cl, 4)

        mst_edges, _ = _kruskal_core_constrained(
            weights, row_idx, col_idx, so, 4, cl_i, cl_p
        )
        # 0-1 and 1-2 accepted; 2-3 rejected (would merge comp with 0 and 3)
        assert mst_edges.shape[0] == 2

    def test_cl_multiple_constraints(self):
        """Multiple CL pairs fragment the graph into multiple components."""
        from fast_hdbscan.kruskal import (
            _kruskal_core_constrained, _validate_cannot_link,
            _get_component_labels_jit,
        )
        # Complete graph on 6 vertices, all weight=1
        n = 6
        tri_r, tri_c = np.triu_indices(n, k=1)
        weights = np.ones(len(tri_r), dtype=np.float64)
        tri_r = tri_r.astype(np.int32)
        tri_c = tri_c.astype(np.int32)
        so = np.arange(len(weights), dtype=np.int32)

        # CL: (0,3), (1,4), (2,5) — forces 3 separate groups
        cl = _make_cl_matrix(n, [(0, 3), (1, 4), (2, 5)])
        cl_i, cl_p = _validate_cannot_link(cl, n)

        mst_edges, preds = _kruskal_core_constrained(
            weights, tri_r, tri_c, so, n, cl_i, cl_p
        )
        labels = _get_component_labels_jit(preds)
        n_comps = len(np.unique(labels))
        # Each CL pair forces at least 2 components; 3 cross-cutting CLs
        # on 6 nodes should give at least 2 components
        assert n_comps >= 2
        # Verify no CL pair shares a component
        for a, b in [(0, 3), (1, 4), (2, 5)]:
            assert labels[a] != labels[b], f"CL pair ({a},{b}) in same component"


class TestCannotLinkValidation:
    """Tests for _validate_cannot_link."""

    def test_upper_triangle_only(self):
        """Upper-triangle CL input produces symmetric CSR."""
        from fast_hdbscan.kruskal import _validate_cannot_link
        cl = _make_cl_matrix(5, [(0, 3), (1, 4)])
        cl_i, cl_p = _validate_cannot_link(cl, 5)
        # Should have 4 entries (2 pairs × 2 directions)
        assert len(cl_i) == 4

    def test_symmetric_input_deduplicates(self):
        """Symmetric CL input is deduplicated to the same result."""
        from fast_hdbscan.kruskal import _validate_cannot_link
        # Build full symmetric CL
        cl_sym = _make_cl_matrix(5, [(0, 3), (1, 4)])
        cl_sym = cl_sym + cl_sym.T
        cl_i, cl_p = _validate_cannot_link(cl_sym, 5)
        assert len(cl_i) == 4

    def test_lower_triangle_input(self):
        """Lower-triangle CL input is also accepted."""
        from fast_hdbscan.kruskal import _validate_cannot_link
        cl_lower = _make_cl_matrix(5, [(3, 0), (4, 1)])  # lower-tri
        cl_i, cl_p = _validate_cannot_link(cl_lower, 5)
        assert len(cl_i) == 4

    def test_diagonal_harmless(self):
        """Diagonal entries are passed through but harmless (self-loops)."""
        from fast_hdbscan.kruskal import _validate_cannot_link
        # Diagonal-only matrix: no real constraints, algorithm should
        # behave identically to unconstrained (self-loops never fire).
        cl = sparse.eye(4, dtype=np.int8, format="csr")
        cl_i, cl_p = _validate_cannot_link(cl, 4)
        # Diagonal entries are kept (no sanitization), but they are
        # harmless self-loops in the conflict list.
        assert len(cl_i) == 4

    def test_empty_cl(self):
        """Empty CL matrix returns empty arrays."""
        from fast_hdbscan.kruskal import _validate_cannot_link
        cl = sparse.csr_matrix((5, 5), dtype=np.int8)
        cl_i, cl_p = _validate_cannot_link(cl, 5)
        assert len(cl_i) == 0
        assert len(cl_p) == 6

    def test_wrong_shape_raises(self):
        """CL matrix with wrong shape raises ValueError."""
        from fast_hdbscan.kruskal import _validate_cannot_link
        cl = sparse.csr_matrix((3, 3), dtype=np.int8)
        with pytest.raises(ValueError, match="does not match"):
            _validate_cannot_link(cl, 5)

    def test_non_sparse_raises(self):
        """Dense array as CL raises ValueError."""
        from fast_hdbscan.kruskal import _validate_cannot_link
        with pytest.raises(ValueError, match="sparse"):
            _validate_cannot_link(np.eye(3), 3)

    def test_validate_false_skips_symmetrization(self):
        """validate=False passes through CSR indices/indptr directly."""
        from fast_hdbscan.kruskal import _validate_cannot_link
        # Build a symmetric CL matrix manually
        cl_sym = _make_cl_matrix(5, [(0, 3), (1, 4)])
        cl_sym = cl_sym + cl_sym.T  # make symmetric
        cl_csr = sparse.csr_matrix(cl_sym)

        cl_i_val, cl_p_val = _validate_cannot_link(cl_csr, 5, validate=True)
        cl_i_novalidate, cl_p_novalidate = _validate_cannot_link(
            cl_csr, 5, validate=False
        )

        # Same result for already-symmetric input
        np.testing.assert_array_equal(
            np.sort(cl_i_novalidate), np.sort(cl_i_val)
        )

    def test_validate_false_entry_point(self):
        """validate_cannot_link=False works through fast_hdbscan()."""
        X = _X_blobs.copy()
        n = X.shape[0]
        # Build symmetric CL
        cl = _make_cl_matrix(n, [(0, 30)])
        cl = cl + cl.T

        labels, probs = fast_hdbscan(
            X, min_cluster_size=5, min_samples=3,
            algorithm="kruskal", knn_k=10, cannot_link=cl,
            validate_cannot_link=False,
        )
        assert labels.shape == (n,)


class TestCannotLinkEntryPoints:
    """Tests for CL constraints through public entry points."""

    def test_feature_matrix_brute_cl(self):
        """knn_k=None (brute-force) with CL constraints."""
        n = 20
        rng = np.random.RandomState(99)
        X = rng.randn(n, 2).astype(np.float64)
        # CL between first and last point
        cl = _make_cl_matrix(n, [(0, n - 1)])

        labels, probs = fast_hdbscan(
            X, min_cluster_size=3, min_samples=2,
            algorithm="kruskal", knn_k=None, cannot_link=cl,
        )
        assert labels.shape == (n,)

    def test_feature_matrix_knn_cl(self):
        """knn_k=10 with CL constraints."""
        X = _X_blobs.copy()
        n = X.shape[0]
        # CL between two points from different blobs
        cl = _make_cl_matrix(n, [(0, 30)])

        labels, probs = fast_hdbscan(
            X, min_cluster_size=5, min_samples=3,
            algorithm="kruskal", knn_k=10, cannot_link=cl,
        )
        assert labels.shape == (n,)

    def test_precomputed_cl(self):
        """metric='precomputed' + algorithm='kruskal' + cannot_link."""
        G = _G_blobs.copy()
        n = G.shape[0]
        cl = _make_cl_matrix(n, [(0, n - 1)])

        labels, probs = fast_hdbscan(
            G, min_cluster_size=5, min_samples=3,
            metric="precomputed", algorithm="kruskal", cannot_link=cl,
        )
        assert labels.shape == (n,)

    def test_hdbscan_class_cl(self):
        """HDBSCAN class API with cannot_link."""
        X = _X_blobs.copy()
        n = X.shape[0]
        cl = _make_cl_matrix(n, [(0, n - 1)])

        h = HDBSCAN(
            min_cluster_size=5, min_samples=3,
            algorithm="kruskal", knn_k=10, cannot_link=cl,
        ).fit(X)
        assert h.labels_.shape == (n,)

    def test_cl_enforced_in_labels(self):
        """Points linked by CL constraint end up in different clusters or noise."""
        # Create well-separated blobs with a cross-blob CL
        rng = np.random.RandomState(7)
        X_a = rng.randn(15, 2) + np.array([-5, 0])
        X_b = rng.randn(15, 2) + np.array([5, 0])
        X = np.vstack([X_a, X_b])
        n = X.shape[0]

        # CL between point 0 (blob A) and point 7 (blob A) — forces split
        cl = _make_cl_matrix(n, [(0, 7)])

        labels, _ = fast_hdbscan(
            X, min_cluster_size=3, min_samples=2,
            algorithm="kruskal", knn_k=None, cannot_link=cl,
        )
        # Either different clusters or at least one is noise
        if labels[0] != -1 and labels[7] != -1:
            assert labels[0] != labels[7], \
                "CL-constrained points should not share a cluster"

    def test_boruvka_with_cl_raises(self):
        """algorithm='boruvka' + cannot_link raises ValueError."""
        cl = _make_cl_matrix(10, [(0, 5)])
        with pytest.raises(ValueError, match="cannot_link"):
            compute_minimum_spanning_tree(
                np.random.randn(10, 2), algorithm="boruvka", cannot_link=cl,
            )

    def test_cl_none_matches_unconstrained(self):
        """cannot_link=None gives identical results to no CL."""
        labels_none, _ = fast_hdbscan(
            _X_blobs, min_cluster_size=5, algorithm="kruskal", knn_k=10,
            cannot_link=None,
        )
        labels_no_param, _ = fast_hdbscan(
            _X_blobs, min_cluster_size=5, algorithm="kruskal", knn_k=10,
        )
        np.testing.assert_array_equal(labels_none, labels_no_param)


# ---------------------------------------------------------------------------
# Accuracy tests for constrained Kruskal
# ---------------------------------------------------------------------------

def _has_cl_violations(predecessors, cl_rows, cl_cols):
    """Vectorized: resolve DSU roots, return True if any CL pair shares one."""
    roots = predecessors.copy()
    while True:
        new_roots = predecessors[roots]
        if np.array_equal(new_roots, roots):
            break
        roots = new_roots
    return np.any(roots[cl_rows] == roots[cl_cols])


class TestCannotLinkAccuracy:
    """Topology, optimality, and stress tests for constrained Kruskal."""

    # ------------------------------------------------------------------
    # Planning-agent topology tests
    # ------------------------------------------------------------------

    def test_transitive_trap(self):
        """A-B(1), C-D(1), B-C(5), CL(A,D).
        Both cheap merges happen first; B-C must be rejected because {A,B}
        and {C,D} carry a transitive conflict."""
        from fast_hdbscan.kruskal import (
            _kruskal_core_constrained, _validate_cannot_link,
            _get_component_labels_jit,
        )
        # A=0 B=1 C=2 D=3
        weights = np.array([1.0, 1.0, 5.0], dtype=np.float64)
        rows = np.array([0, 2, 1], dtype=np.int32)
        cols = np.array([1, 3, 2], dtype=np.int32)
        so = np.argsort(weights, kind="stable").astype(np.int32)

        cl = _make_cl_matrix(4, [(0, 3)])
        cl_i, cl_p = _validate_cannot_link(cl, 4)

        mst, preds = _kruskal_core_constrained(
            weights, rows, cols, so, 4, cl_i, cl_p
        )
        labels = _get_component_labels_jit(preds)
        # Two components: {A,B} and {C,D}
        assert len(np.unique(labels)) == 2
        assert labels[0] == labels[1]  # A,B together
        assert labels[2] == labels[3]  # C,D together
        assert labels[0] != labels[2]  # separated
        # Exactly 2 edges accepted (A-B, C-D); B-C rejected
        assert mst.shape[0] == 2

    def test_redundant_constraint(self):
        """Triangle A-C(1), B-C(2), A-B(3), CL(A,B).
        A-C merges first.  Then B-C is rejected because B's constraint
        against A is inherited by the {A,C} component.  A-B also rejected."""
        from fast_hdbscan.kruskal import (
            _kruskal_core_constrained, _validate_cannot_link,
            _get_component_labels_jit,
        )
        # A=0, B=1, C=2.  Edges sorted by weight: A-C(1), B-C(2), A-B(3).
        weights = np.array([1.0, 2.0, 3.0], dtype=np.float64)
        rows = np.array([0, 1, 0], dtype=np.int32)
        cols = np.array([2, 2, 1], dtype=np.int32)
        so = np.argsort(weights, kind="stable").astype(np.int32)

        cl = _make_cl_matrix(3, [(0, 1)])
        cl_i, cl_p = _validate_cannot_link(cl, 3)

        mst, preds = _kruskal_core_constrained(
            weights, rows, cols, so, 3, cl_i, cl_p
        )
        labels = _get_component_labels_jit(preds)
        # Only A-C accepted.  B isolated.
        assert mst.shape[0] == 1
        assert labels[0] == labels[2]
        assert labels[1] != labels[0]

    def test_fully_constrained(self):
        """Every pair constrained -> zero edges accepted."""
        from fast_hdbscan.kruskal import (
            _kruskal_core_constrained, _validate_cannot_link,
        )
        n = 6
        tri_r, tri_c = np.triu_indices(n, k=1)
        weights = np.arange(len(tri_r), dtype=np.float64)
        tri_r = tri_r.astype(np.int32)
        tri_c = tri_c.astype(np.int32)
        so = np.argsort(weights, kind="stable").astype(np.int32)

        # All pairs constrained
        cl_pairs = list(zip(tri_r.tolist(), tri_c.tolist()))
        cl = _make_cl_matrix(n, cl_pairs)
        cl_i, cl_p = _validate_cannot_link(cl, n)

        mst, _ = _kruskal_core_constrained(
            weights, tri_r, tri_c, so, n, cl_i, cl_p
        )
        assert mst.shape[0] == 0

    def test_scipy_equivalence_unconstrained(self):
        """Empty constraints -> MST weight matches scipy.sparse.csgraph."""
        from scipy.sparse.csgraph import minimum_spanning_tree as scipy_mst
        from fast_hdbscan.kruskal import _kruskal_core

        G = _make_connected_sparse_graph(n=20, seed=42)
        n = G.shape[0]

        # scipy MST
        sp_weight = scipy_mst(G).data.sum()

        # Our Kruskal on upper-triangle edges
        upper = sparse.triu(G, k=1).tocoo()
        rows = upper.row.astype(np.int32)
        cols = upper.col.astype(np.int32)
        weights = upper.data.astype(np.float64)
        so = np.argsort(weights, kind="stable").astype(np.int32)

        mst, _ = _kruskal_core(weights, rows, cols, so, n)
        np.testing.assert_allclose(mst[:, 2].sum(), sp_weight, rtol=1e-10)

    # ------------------------------------------------------------------
    # Universal validator (stress)
    # ------------------------------------------------------------------

    def test_universal_validator_random_stress(self):
        """Random graphs x random CL: no violations, min 100 trials, max 10s."""
        import time
        from fast_hdbscan.kruskal import (
            _kruskal_core_constrained, _validate_cannot_link,
        )

        min_trials = 100
        max_seconds = 10.0
        start = time.perf_counter()
        trial = 0
        while trial < min_trials or time.perf_counter() - start < max_seconds:
            rng = np.random.RandomState(trial + 7000)
            n = rng.randint(10, 45)
            tri_r, tri_c = np.triu_indices(n, k=1)
            n_possible = len(tri_r)

            # Edge graph: 40-70% density
            n_edges = rng.randint(
                max(n, int(n_possible * 0.4)),
                max(n + 1, int(n_possible * 0.7) + 1),
            )
            n_edges = min(n_edges, n_possible)
            idx = rng.choice(n_possible, n_edges, replace=False)
            rows = tri_r[idx].astype(np.int32)
            cols = tri_c[idx].astype(np.int32)
            weights = rng.uniform(0.1, 10.0, n_edges).astype(np.float64)
            so = np.argsort(weights, kind="stable").astype(np.int32)

            # CL: 10-30% density
            n_cl = rng.randint(
                max(1, int(n_possible * 0.1)),
                max(2, int(n_possible * 0.3) + 1),
            )
            n_cl = min(n_cl, n_possible)
            cl_idx = rng.choice(n_possible, n_cl, replace=False)
            cl_rows = tri_r[cl_idx]
            cl_cols = tri_c[cl_idx]
            cl_data = np.ones(n_cl, dtype=np.int8)
            cl_mat = sparse.csr_matrix(
                (cl_data, (cl_rows, cl_cols)), shape=(n, n)
            )
            cl_i, cl_p = _validate_cannot_link(cl_mat, n)

            _, preds = _kruskal_core_constrained(
                weights, rows, cols, so, n, cl_i, cl_p
            )
            assert not _has_cl_violations(preds, cl_rows, cl_cols), (
                f"CL violation at trial {trial} (n={n}, "
                f"edges={n_edges}, cl={n_cl}, seed={trial + 7000})"
            )
            trial += 1

        elapsed = time.perf_counter() - start
        assert trial >= min_trials, f"Only {trial} trials completed"
        # Diagnostic: print throughput so we can gauge CI performance
        rate = trial / elapsed
        print(f"\n  stress: {trial} trials in {elapsed:.2f}s ({rate:.0f} trials/s)")

    # ------------------------------------------------------------------
    # Non-interference
    # ------------------------------------------------------------------

    def test_non_interference(self):
        """CL between nodes already in different MST components
        produces bitwise-identical edges."""
        from fast_hdbscan.kruskal import (
            _kruskal_core, _kruskal_core_constrained,
            _validate_cannot_link, _get_component_labels_jit,
        )
        rng = np.random.RandomState(55)
        n = 20
        half = n // 2

        # Two disconnected complete subgraphs: [0, half) and [half, n)
        pairs = []
        for i in range(half):
            for j in range(i + 1, half):
                pairs.append((i, j))
        for i in range(half, n):
            for j in range(i + 1, n):
                pairs.append((i, j))
        pairs = np.array(pairs)
        weights = rng.uniform(0.1, 5.0, len(pairs)).astype(np.float64)
        rows = pairs[:, 0].astype(np.int32)
        cols = pairs[:, 1].astype(np.int32)
        so = np.argsort(weights, kind="stable").astype(np.int32)

        # Unconstrained
        mst_u, preds_u = _kruskal_core(weights, rows, cols, so, n)
        labels = _get_component_labels_jit(preds_u)
        assert len(np.unique(labels)) == 2, "graph should be disconnected"
        assert labels[0] != labels[half], "nodes 0 and half should be in different components"

        # Constrained: CL between one node in each component
        cl = _make_cl_matrix(n, [(0, half)])
        cl_i, cl_p = _validate_cannot_link(cl, n)
        mst_c, _ = _kruskal_core_constrained(
            weights, rows, cols, so, n, cl_i, cl_p
        )

        np.testing.assert_array_equal(mst_u, mst_c)

    # ------------------------------------------------------------------
    # Dynamic transitivity
    # ------------------------------------------------------------------

    def test_dynamic_transitivity(self):
        """Line A-B(10), B-C(1), C-D(10), CL(A,D).
        B-C is cheapest, so {B,C} forms first.  A-B merges A into {B,C}
        (no conflict — D is still isolated).  Then C-D must be rejected
        because A is now in {A,B,C} and CL(A,D) blocks the merge."""
        from fast_hdbscan.kruskal import (
            _kruskal_core_constrained, _validate_cannot_link,
        )
        # A=0, B=1, C=2, D=3
        weights = np.array([10.0, 1.0, 10.0], dtype=np.float64)
        rows = np.array([0, 1, 2], dtype=np.int32)
        cols = np.array([1, 2, 3], dtype=np.int32)
        so = np.argsort(weights, kind="stable").astype(np.int32)

        cl = _make_cl_matrix(4, [(0, 3)])
        cl_i, cl_p = _validate_cannot_link(cl, 4)

        mst, preds = _kruskal_core_constrained(
            weights, rows, cols, so, 4, cl_i, cl_p
        )

        # Two edges accepted: B-C(1) and A-B(10)
        assert mst.shape[0] == 2
        edge_pairs = set(
            (int(mst[i, 0]), int(mst[i, 1])) for i in range(mst.shape[0])
        )
        assert (1, 2) in edge_pairs, "B-C should be in MSF"
        assert (0, 1) in edge_pairs, "A-B should be in MSF"
        assert (2, 3) not in edge_pairs, "C-D must be rejected"


# ---------------------------------------------------------------------------
# Forest clustering tests (clusters_from_spanning_forest)
# ---------------------------------------------------------------------------

def _check_cl_violations(labels, cl_pairs):
    """Return list of CL pairs assigned to the same non-noise cluster."""
    return [
        (i, j)
        for i, j in cl_pairs
        if labels[i] != -1 and labels[j] != -1 and labels[i] == labels[j]
    ]


def _build_3comp_precomputed(n=30):
    """Build precomputed graph with 3 MSF components after CL extraction.

    Clique A: nodes 0..14 (excluding node 10)
    Singleton: node 10 (CL'd against all clique A members)
    Clique B: nodes 15..29 (disconnected from A)

    Returns (G, cl, cl_pairs) where G is sparse distance matrix, cl is
    CL constraint matrix, cl_pairs is list of (i,j) CL tuples.
    """
    rows, cols, data = [], [], []
    clique_a = [i for i in range(15) if i != 10]
    for i, ni in enumerate(clique_a):
        for j in range(i + 1, len(clique_a)):
            nj = clique_a[j]
            w = 1.0 + 0.001 * abs(ni - nj)
            rows += [ni, nj]; cols += [nj, ni]; data += [w, w]
    for nbr in [8, 9, 11, 12]:
        rows += [10, nbr]; cols += [nbr, 10]; data += [0.5, 0.5]
    for i in range(15, n):
        for j in range(i + 1, n):
            w = 1.0 + 0.001 * abs(i - j)
            rows += [i, j]; cols += [j, i]; data += [w, w]
    G = sparse.csr_matrix((data, (rows, cols)), shape=(n, n), dtype=np.float64)
    cl_pairs = [(10, nbr) for nbr in clique_a]
    cl_rows = [p[0] for p in cl_pairs]
    cl_cols = [p[1] for p in cl_pairs]
    cl = sparse.csr_matrix(
        (np.ones(len(cl_pairs), dtype=np.int8), (cl_rows, cl_cols)),
        shape=(n, n),
    )
    return G, cl, cl_pairs


class TestForestClustering:
    """Tests for clusters_from_spanning_forest: per-component cluster selection."""

    def test_3comp_no_violation_precomputed(self):
        """3 MSF components (precomputed): zero CL violations for EOM and leaf."""
        G, cl, cl_pairs = _build_3comp_precomputed()
        for mcs in [2, 5, 10]:
            for method in ["eom", "leaf"]:
                labels, _ = fast_hdbscan(
                    G, min_cluster_size=mcs, min_samples=1,
                    metric="precomputed", algorithm="kruskal",
                    cannot_link=cl, cluster_selection_method=method,
                )
                v = _check_cl_violations(labels, cl_pairs)
                assert len(v) == 0, (
                    f"CL violation (precomputed mcs={mcs} {method}): {v}"
                )

    def test_3comp_no_violation_euclidean_brute(self):
        """3 MSF components (euclidean brute): zero CL violations."""
        rng = np.random.RandomState(42)
        X = np.vstack([
            rng.randn(15, 2) * 0.2 + [-5, 0],
            rng.randn(15, 2) * 0.2 + [5, 0],
        ])
        n = X.shape[0]
        target = 7
        cl_pairs = [(target, j) for j in range(15) if j != target]
        cl = _make_cl_matrix(n, cl_pairs)

        for mcs in [2, 5, 10]:
            for method in ["eom", "leaf"]:
                labels, _ = fast_hdbscan(
                    X, min_cluster_size=mcs, min_samples=2,
                    algorithm="kruskal", knn_k=None, cannot_link=cl,
                    cluster_selection_method=method,
                )
                v = _check_cl_violations(labels, cl_pairs)
                assert len(v) == 0, (
                    f"CL violation (brute mcs={mcs} {method}): {v}"
                )

    def test_3comp_no_violation_euclidean_knn(self):
        """3 MSF components (euclidean knn): zero CL violations."""
        rng = np.random.RandomState(42)
        X = np.vstack([
            rng.randn(15, 2) * 0.2 + [-5, 0],
            rng.randn(15, 2) * 0.2 + [5, 0],
        ])
        n = X.shape[0]
        target = 7
        cl_pairs = [(target, j) for j in range(15) if j != target]
        cl = _make_cl_matrix(n, cl_pairs)

        for mcs in [2, 5, 10]:
            for method in ["eom", "leaf"]:
                labels, _ = fast_hdbscan(
                    X, min_cluster_size=mcs, min_samples=2,
                    algorithm="kruskal", knn_k=10, cannot_link=cl,
                    cluster_selection_method=method,
                )
                v = _check_cl_violations(labels, cl_pairs)
                assert len(v) == 0, (
                    f"CL violation (knn mcs={mcs} {method}): {v}"
                )

    def test_singleton_is_noise(self):
        """A singleton MSF component (node CL'd against all others) is noise."""
        G, cl, _ = _build_3comp_precomputed()
        labels, _ = fast_hdbscan(
            G, min_cluster_size=5, min_samples=1,
            metric="precomputed", algorithm="kruskal", cannot_link=cl,
        )
        assert labels[10] == -1, "Singleton component should be noise"

    def test_small_comp_is_noise(self):
        """Components smaller than min_cluster_size are all noise."""
        # Build a graph where CL creates a 3-node component (< mcs=5)
        n = 20
        rows, cols, data = [], [], []
        # Group A: nodes 0..9
        for i in range(10):
            for j in range(i + 1, 10):
                rows += [i, j]; cols += [j, i]; data += [1.0, 1.0]
        # Group B: nodes 10..12 (3 nodes — too small for mcs=5)
        for i in range(10, 13):
            for j in range(i + 1, 13):
                rows += [i, j]; cols += [j, i]; data += [1.0, 1.0]
        # Group C: nodes 13..19
        for i in range(13, n):
            for j in range(i + 1, n):
                rows += [i, j]; cols += [j, i]; data += [1.0, 1.0]
        G = sparse.csr_matrix((data, (rows, cols)), shape=(n, n), dtype=np.float64)

        # CL between group B and groups A/C to keep them separate
        cl_pairs = [(10, 0), (10, 13)]  # Minimal CL to disconnect
        cl = _make_cl_matrix(n, cl_pairs)

        labels, _ = fast_hdbscan(
            G, min_cluster_size=5, min_samples=1,
            metric="precomputed", algorithm="kruskal", cannot_link=cl,
        )
        # Group B (nodes 10-12) should all be noise since comp size=3 < mcs=5
        assert all(labels[i] == -1 for i in range(10, 13)), \
            f"Small component should be noise, got: {labels[10:13]}"

    def test_large_comps_independent_labels(self):
        """Two large components get independent cluster labels."""
        # Use euclidean data with well-separated blobs for clear density structure
        rng = np.random.RandomState(42)
        X = np.vstack([
            rng.randn(15, 2) * 0.2 + [-5, 0],  # blob A
            rng.randn(15, 2) * 0.2 + [5, 0],    # blob B
        ])
        n = X.shape[0]
        # CL node 7 vs all other blob A members -> 3 components
        cl_pairs = [(7, j) for j in range(15) if j != 7]
        cl = _make_cl_matrix(n, cl_pairs)

        labels, _ = fast_hdbscan(
            X, min_cluster_size=5, min_samples=2,
            algorithm="kruskal", knn_k=None, cannot_link=cl,
        )
        # Blob A (minus node 7) and Blob B should each have a cluster
        a_labels = set(labels[i] for i in range(15) if i != 7 and labels[i] != -1)
        b_labels = set(labels[i] for i in range(15, 30) if labels[i] != -1)
        assert len(a_labels) > 0, f"Blob A should have clusters, got: {labels[:15]}"
        assert len(b_labels) > 0, f"Blob B should have clusters, got: {labels[15:]}"
        assert a_labels.isdisjoint(b_labels), \
            f"Components should have distinct labels: A={a_labels}, B={b_labels}"

    def test_no_cl_no_forest_path(self):
        """Without CL, forest path is not used — same results as before."""
        labels_no_cl, _ = fast_hdbscan(
            _X_blobs, min_cluster_size=5, algorithm="kruskal", knn_k=10,
        )
        labels_none_cl, _ = fast_hdbscan(
            _X_blobs, min_cluster_size=5, algorithm="kruskal", knn_k=10,
            cannot_link=None,
        )
        np.testing.assert_array_equal(labels_no_cl, labels_none_cl)

    def test_single_component_no_split(self):
        """CL that doesn't separate anything -> single component -> normal path."""
        rng = np.random.RandomState(99)
        X = rng.randn(50, 2) * 0.3 + [0, 0]
        # CL between very far points in different natural clusters
        # But with a single blob there's no split — CL prevents merge of these
        # two points' components, but they're in the same blob.
        # With a single tight blob and CL(0,1), node 1 becomes a singleton.
        cl = _make_cl_matrix(50, [(0, 1)])
        labels, _ = fast_hdbscan(
            X, min_cluster_size=5, min_samples=2,
            algorithm="kruskal", knn_k=10, cannot_link=cl,
        )
        # Both should be either in different clusters or one is noise
        if labels[0] != -1 and labels[1] != -1:
            assert labels[0] != labels[1]

    def test_all_singletons_all_noise(self):
        """Every pair constrained -> all singletons -> all noise."""
        n = 6
        all_pairs = [(i, j) for i in range(n) for j in range(i + 1, n)]
        cl = _make_cl_matrix(n, all_pairs)
        X = np.random.RandomState(42).randn(n, 2)
        labels, _ = fast_hdbscan(
            X, min_cluster_size=2, min_samples=1,
            algorithm="kruskal", knn_k=None, cannot_link=cl,
        )
        assert np.all(labels == -1), f"All singletons should be noise, got: {labels}"

    def test_hdbscan_class_forest_no_violations(self):
        """HDBSCAN class API with CL: no violations in labels."""
        G, cl, cl_pairs = _build_3comp_precomputed()
        h = HDBSCAN(
            min_cluster_size=5, min_samples=1,
            metric="precomputed", algorithm="kruskal", cannot_link=cl,
        ).fit(G)
        v = _check_cl_violations(h.labels_, cl_pairs)
        assert len(v) == 0, f"HDBSCAN class CL violations: {v}"

    def test_forest_return_trees(self):
        """Forest path returns valid tree structures."""
        G, cl, _ = _build_3comp_precomputed()
        result = fast_hdbscan(
            G, min_cluster_size=5, min_samples=1,
            metric="precomputed", algorithm="kruskal",
            cannot_link=cl, return_trees=True,
        )
        labels, probs, linkage_tree, condensed_tree, sorted_mst, neighbors, core_dists = result
        assert labels.shape == (30,)
        assert probs.shape == (30,)
        assert linkage_tree.shape[1] == 4  # standard linkage format
        assert sorted_mst.shape[0] == 29  # n-1 edges (bridged for trees)
        assert sorted_mst.shape[1] == 3

    def test_forest_allow_single_cluster(self):
        """allow_single_cluster with forest: no CL violations."""
        G, cl, cl_pairs = _build_3comp_precomputed()
        for method in ["eom", "leaf"]:
            labels, _ = fast_hdbscan(
                G, min_cluster_size=5, min_samples=1,
                metric="precomputed", algorithm="kruskal",
                cannot_link=cl, cluster_selection_method=method,
                allow_single_cluster=True,
            )
            v = _check_cl_violations(labels, cl_pairs)
            assert len(v) == 0, (
                f"allow_single_cluster CL violation ({method}): {v}"
            )

    def test_forest_epsilon_selection(self):
        """cluster_selection_epsilon with forest: no CL violations."""
        G, cl, cl_pairs = _build_3comp_precomputed()
        labels, _ = fast_hdbscan(
            G, min_cluster_size=5, min_samples=1,
            metric="precomputed", algorithm="kruskal",
            cannot_link=cl, cluster_selection_epsilon=0.5,
        )
        v = _check_cl_violations(labels, cl_pairs)
        assert len(v) == 0, f"epsilon selection CL violations: {v}"

    def test_forest_persistence_selection(self):
        """cluster_selection_persistence with CL: no violations."""
        G, cl, cl_pairs = _build_3comp_precomputed()
        labels, _ = fast_hdbscan(
            G, min_cluster_size=2, min_samples=1,
            metric="precomputed", algorithm="kruskal",
            cannot_link=cl, cluster_selection_persistence=0.1,
        )
        v = _check_cl_violations(labels, cl_pairs)
        assert len(v) == 0, f"persistence selection CL violations: {v}"

    def test_forest_stress_random(self):
        """Random feature data x random CL: no violations in final labels."""
        import time
        min_trials = 20
        max_seconds = 10.0
        start = time.perf_counter()
        trial = 0
        while trial < min_trials or time.perf_counter() - start < max_seconds:
            rng = np.random.RandomState(trial + 9000)
            n = rng.randint(20, 60)
            X = rng.randn(n, 3)

            # Random CL: 5-15% of all pairs
            tri_r, tri_c = np.triu_indices(n, k=1)
            n_possible = len(tri_r)
            n_cl = rng.randint(
                max(1, int(n_possible * 0.05)),
                max(2, int(n_possible * 0.15) + 1),
            )
            n_cl = min(n_cl, n_possible)
            cl_idx = rng.choice(n_possible, n_cl, replace=False)
            cl_pairs_arr = list(zip(tri_r[cl_idx].tolist(), tri_c[cl_idx].tolist()))
            cl = _make_cl_matrix(n, cl_pairs_arr)

            mcs = rng.choice([2, 3, 5])
            method = rng.choice(["eom", "leaf"])

            labels, _ = fast_hdbscan(
                X, min_cluster_size=mcs, min_samples=2,
                algorithm="kruskal", knn_k=None, cannot_link=cl,
                cluster_selection_method=method,
            )
            v = _check_cl_violations(labels, cl_pairs_arr)
            assert len(v) == 0, (
                f"CL violation at trial {trial} (n={n}, mcs={mcs}, "
                f"{method}, seed={trial + 9000}): {v}"
            )
            trial += 1

        elapsed = time.perf_counter() - start
        print(f"\n  forest stress: {trial} trials in {elapsed:.2f}s")


# ---------------------------------------------------------------------------
# Group-label cannot-link tests
# ---------------------------------------------------------------------------

from fast_hdbscan.kruskal import (
    _kruskal_core_group_constrained,
    _validate_cannot_link_groups,
    _get_component_labels_jit,
)


def _groups_to_cl_pairs(group_labels):
    """Convert group labels to a list of (i, j) CL pairs (i < j)."""
    pairs = []
    groups = {}
    for idx, g in enumerate(group_labels):
        if g < 0:
            continue
        groups.setdefault(g, []).append(idx)
    for members in groups.values():
        for a_idx in range(len(members)):
            for b_idx in range(a_idx + 1, len(members)):
                pairs.append((members[a_idx], members[b_idx]))
    return pairs


def _groups_to_cl_matrix(group_labels):
    """Convert group labels to a sparse CL matrix (upper-triangle)."""
    pairs = _groups_to_cl_pairs(group_labels)
    n = len(group_labels)
    if not pairs:
        return sparse.csr_matrix((n, n), dtype=np.int8)
    rows, cols = zip(*pairs)
    data = np.ones(len(pairs), dtype=np.int8)
    return sparse.csr_matrix((data, (rows, cols)), shape=(n, n))


class TestCannotLinkGroupsValidation:
    """Tests for _validate_cannot_link_groups."""

    def test_valid_basic(self):
        """Basic valid input returns correct group_labels and n_groups."""
        labels = np.array([0, 1, 2, 0, 1], dtype=np.int32)
        gl, ng = _validate_cannot_link_groups(labels, 5)
        np.testing.assert_array_equal(gl, labels)
        assert ng == 3  # max(2) + 1

    def test_all_unconstrained(self):
        """All -1 labels returns n_groups=0."""
        labels = np.array([-1, -1, -1, -1], dtype=np.int32)
        gl, ng = _validate_cannot_link_groups(labels, 4)
        assert ng == 0
        np.testing.assert_array_equal(gl, labels)

    def test_wrong_length_raises(self):
        """Array with wrong length raises ValueError."""
        labels = np.array([0, 1, 2], dtype=np.int32)
        with pytest.raises(ValueError, match="does not match"):
            _validate_cannot_link_groups(labels, 5)

    def test_values_below_minus_one_raises(self):
        """Values < -1 raise ValueError."""
        labels = np.array([0, -2, 1], dtype=np.int32)
        with pytest.raises(ValueError, match="values >= -1"):
            _validate_cannot_link_groups(labels, 3)

    def test_mixed_unconstrained_and_groups(self):
        """Mixed -1 and non-negative: n_groups = max + 1."""
        labels = np.array([-1, 0, -1, 2, 1], dtype=np.int32)
        gl, ng = _validate_cannot_link_groups(labels, 5)
        assert ng == 3  # max(2) + 1
        np.testing.assert_array_equal(gl, labels)

    def test_non_contiguous_group_ids(self):
        """Non-contiguous group IDs (e.g. 0, 3, 7): n_groups = max + 1 = 8."""
        labels = np.array([0, 3, 7, 0, 3], dtype=np.int32)
        gl, ng = _validate_cannot_link_groups(labels, 5)
        assert ng == 8  # max(7) + 1


class TestCannotLinkGroupsCore:
    """Tests for _kruskal_core_group_constrained JIT function."""

    def test_basic_prevents_same_group_merge(self):
        """3-node path 0--1--2, group_labels=[0,1,0] -> can't merge 0 and 2."""
        weights = np.array([1.0, 2.0], dtype=np.float64)
        row_idx = np.array([0, 1], dtype=np.int32)
        col_idx = np.array([1, 2], dtype=np.int32)
        sorted_order = np.array([0, 1], dtype=np.int32)
        group_labels = np.array([0, 1, 0], dtype=np.int32)

        mst_edges, preds = _kruskal_core_group_constrained(
            weights, row_idx, col_idx, sorted_order, 3,
            group_labels, 2,  # n_groups=2
        )
        # Edge 0-1 accepted (groups 0,1 — no conflict).
        # Edge 1-2 rejected: merging {0,1} with {2} would put two group-0
        # vertices in one component.
        assert mst_edges.shape[0] == 1
        assert int(mst_edges[0, 0]) == 0 and int(mst_edges[0, 1]) == 1

    def test_all_unconstrained_matches_unconstrained(self):
        """All -1 group labels give same result as unconstrained Kruskal."""
        from fast_hdbscan.kruskal import _kruskal_core

        rng = np.random.RandomState(42)
        n = 8
        tri_r, tri_c = np.triu_indices(n, k=1)
        weights = rng.uniform(0.1, 5.0, size=len(tri_r)).astype(np.float64)
        tri_r = tri_r.astype(np.int32)
        tri_c = tri_c.astype(np.int32)
        so = np.argsort(weights, kind="stable").astype(np.int32)

        group_labels = np.full(n, -1, dtype=np.int32)

        mst_u, _ = _kruskal_core(weights, tri_r, tri_c, so, n)
        mst_g, _ = _kruskal_core_group_constrained(
            weights, tri_r, tri_c, so, n, group_labels, 0,
        )
        np.testing.assert_array_equal(mst_u, mst_g)

    def test_all_same_group_blocks_everything(self):
        """All vertices in group 0 -> every edge blocked -> 0 MST edges."""
        n = 5
        tri_r, tri_c = np.triu_indices(n, k=1)
        weights = np.arange(len(tri_r), dtype=np.float64) + 1.0
        tri_r = tri_r.astype(np.int32)
        tri_c = tri_c.astype(np.int32)
        so = np.argsort(weights, kind="stable").astype(np.int32)
        group_labels = np.zeros(n, dtype=np.int32)

        mst_edges, _ = _kruskal_core_group_constrained(
            weights, tri_r, tri_c, so, n, group_labels, 1,
        )
        assert mst_edges.shape[0] == 0

    def test_transitive_chain(self):
        """Chain 0-1-2-3, labels=[0,-1,-1,0] -> blocks merging 0 and 3."""
        weights = np.array([1.0, 2.0, 3.0], dtype=np.float64)
        row_idx = np.array([0, 1, 2], dtype=np.int32)
        col_idx = np.array([1, 2, 3], dtype=np.int32)
        so = np.argsort(weights, kind="stable").astype(np.int32)
        group_labels = np.array([0, -1, -1, 0], dtype=np.int32)

        mst_edges, preds = _kruskal_core_group_constrained(
            weights, row_idx, col_idx, so, 4, group_labels, 1,
        )
        # 0-1(1) accepted, 1-2(2) accepted, 2-3(3) rejected
        # (merging {0,1,2} with {3} would put two group-0 vertices together)
        assert mst_edges.shape[0] == 2
        labels = _get_component_labels_jit(preds)
        assert labels[0] != labels[3], "Transitive CL: 0 and 3 must be separated"
        assert labels[0] == labels[1] == labels[2], "0,1,2 should be in same component"


class TestCannotLinkGroupsEntryPoints:
    """Tests for cannot_link_groups through public entry points."""

    def test_fast_hdbscan_brute(self):
        """fast_hdbscan() with cannot_link_groups via brute-force (knn_k=None)."""
        n = _X_blobs.shape[0]
        group_labels = np.full(n, -1, dtype=np.int32)
        # Assign first 20 samples to group 0 and last 20 to group 1
        group_labels[:20] = 0
        group_labels[-20:] = 1

        labels, probs = fast_hdbscan(
            _X_blobs, min_cluster_size=5, min_samples=3,
            algorithm="kruskal", knn_k=None,
            cannot_link_groups=group_labels,
        )
        assert labels.shape == (n,)

    def test_fast_hdbscan_knn(self):
        """fast_hdbscan() with cannot_link_groups via KNN (knn_k=10)."""
        n = _X_blobs.shape[0]
        group_labels = np.full(n, -1, dtype=np.int32)
        group_labels[:20] = 0
        group_labels[-20:] = 1

        labels, probs = fast_hdbscan(
            _X_blobs, min_cluster_size=5, min_samples=3,
            algorithm="kruskal", knn_k=10,
            cannot_link_groups=group_labels,
        )
        assert labels.shape == (n,)

    def test_compute_minimum_spanning_tree(self):
        """compute_minimum_spanning_tree() with cannot_link_groups."""
        n = _X_blobs.shape[0]
        group_labels = np.full(n, -1, dtype=np.int32)
        group_labels[:20] = 0

        mst, neighbors, core_dists = compute_minimum_spanning_tree(
            _X_blobs, min_samples=5, algorithm="kruskal", knn_k=10,
            cannot_link_groups=group_labels,
        )
        assert mst.shape[0] == n - 1
        assert mst.shape[1] == 3

    def test_hdbscan_class(self):
        """HDBSCAN class with cannot_link_groups."""
        n = _X_blobs.shape[0]
        group_labels = np.full(n, -1, dtype=np.int32)
        group_labels[:20] = 0
        group_labels[-20:] = 1

        h = HDBSCAN(
            min_cluster_size=5, min_samples=3,
            algorithm="kruskal", knn_k=10,
            cannot_link_groups=group_labels,
        ).fit(_X_blobs)
        assert h.labels_.shape == (n,)

    def test_precomputed(self):
        """metric='precomputed' + cannot_link_groups."""
        n = _G_blobs.shape[0]
        group_labels = np.full(n, -1, dtype=np.int32)
        group_labels[:20] = 0
        group_labels[-20:] = 1

        labels, probs = fast_hdbscan(
            _G_blobs, min_cluster_size=5, min_samples=3,
            metric="precomputed", algorithm="kruskal",
            cannot_link_groups=group_labels,
        )
        assert labels.shape == (n,)

    def test_both_cl_and_groups_raises(self):
        """Providing both cannot_link and cannot_link_groups raises ValueError."""
        n = _X_blobs.shape[0]
        cl = _make_cl_matrix(n, [(0, n - 1)])
        group_labels = np.zeros(n, dtype=np.int32)

        with pytest.raises(ValueError, match="mutually exclusive"):
            fast_hdbscan(
                _X_blobs, min_cluster_size=5, min_samples=3,
                algorithm="kruskal", knn_k=10,
                cannot_link=cl, cannot_link_groups=group_labels,
            )

    def test_boruvka_with_groups_raises(self):
        """algorithm='boruvka' + cannot_link_groups raises ValueError."""
        n = 10
        group_labels = np.zeros(n, dtype=np.int32)
        with pytest.raises(ValueError, match="cannot_link"):
            compute_minimum_spanning_tree(
                np.random.randn(n, 2), algorithm="boruvka",
                cannot_link_groups=group_labels,
            )

    def test_cl_enforced_in_labels(self):
        """Same-group samples end up in different clusters or noise."""
        rng = np.random.RandomState(7)
        X_a = rng.randn(15, 2) + np.array([-5, 0])
        X_b = rng.randn(15, 2) + np.array([5, 0])
        X = np.vstack([X_a, X_b])
        n = X.shape[0]

        # All of blob A in group 0 -> they can't co-cluster
        group_labels = np.full(n, -1, dtype=np.int32)
        group_labels[:15] = 0

        labels, _ = fast_hdbscan(
            X, min_cluster_size=3, min_samples=2,
            algorithm="kruskal", knn_k=None,
            cannot_link_groups=group_labels,
        )
        # Check no two group-0 samples share a non-noise cluster
        group_0_labels = labels[:15]
        non_noise = group_0_labels[group_0_labels != -1]
        if len(non_noise) > 0:
            # Each non-noise sample must be in its own cluster (all same-group)
            assert len(set(non_noise)) == len(non_noise), (
                f"Same-group samples share clusters: {non_noise}"
            )


class TestCannotLinkGroupsEquivalence:
    """Group labels produce same results as equivalent sparse CL matrix."""

    def test_small_case_identical_mst(self):
        """Small case (n=20, 4 groups): identical MST edges vs sparse matrix."""
        from fast_hdbscan.kruskal import (
            _kruskal_core_constrained, _validate_cannot_link,
        )

        rng = np.random.RandomState(123)
        n = 20
        # Assign 4 groups of 5 samples each
        group_labels = np.repeat(np.arange(4, dtype=np.int32), 5)

        # Build equivalent sparse CL matrix
        cl_mat = _groups_to_cl_matrix(group_labels)
        cl_i, cl_p = _validate_cannot_link(cl_mat, n)

        # Build a random complete graph
        tri_r, tri_c = np.triu_indices(n, k=1)
        weights = rng.uniform(0.1, 5.0, size=len(tri_r)).astype(np.float64)
        tri_r = tri_r.astype(np.int32)
        tri_c = tri_c.astype(np.int32)
        so = np.argsort(weights, kind="stable").astype(np.int32)

        # Sparse-matrix CL
        mst_sparse, _ = _kruskal_core_constrained(
            weights, tri_r, tri_c, so, n, cl_i, cl_p
        )

        # Group-label CL
        mst_group, _ = _kruskal_core_group_constrained(
            weights, tri_r, tri_c, so, n, group_labels, 4,
        )

        np.testing.assert_array_equal(
            mst_sparse, mst_group,
            err_msg="Group-label and sparse CL MST edges differ",
        )

    def test_mixed_constrained_unconstrained(self):
        """Mixed -1 and non-negative labels: equivalence with sparse matrix."""
        from fast_hdbscan.kruskal import (
            _kruskal_core_constrained, _validate_cannot_link,
        )

        rng = np.random.RandomState(456)
        n = 20
        # Some samples constrained, some unconstrained
        group_labels = np.array(
            [0, -1, 1, -1, 0, 1, -1, -1, 2, 2,
             -1, 0, -1, 1, -1, 2, -1, -1, 0, 1],
            dtype=np.int32,
        )

        cl_mat = _groups_to_cl_matrix(group_labels)
        cl_i, cl_p = _validate_cannot_link(cl_mat, n)

        tri_r, tri_c = np.triu_indices(n, k=1)
        weights = rng.uniform(0.1, 5.0, size=len(tri_r)).astype(np.float64)
        tri_r = tri_r.astype(np.int32)
        tri_c = tri_c.astype(np.int32)
        so = np.argsort(weights, kind="stable").astype(np.int32)

        mst_sparse, _ = _kruskal_core_constrained(
            weights, tri_r, tri_c, so, n, cl_i, cl_p
        )
        n_groups = int(group_labels.max()) + 1
        mst_group, _ = _kruskal_core_group_constrained(
            weights, tri_r, tri_c, so, n, group_labels, n_groups,
        )

        np.testing.assert_array_equal(
            mst_sparse, mst_group,
            err_msg="Mixed constrained/unconstrained MST edges differ",
        )

    def test_stress_no_violations(self):
        """Random data, random groups, verify no CL violations (20+ trials)."""
        import time

        min_trials = 20
        max_seconds = 10.0
        start = time.perf_counter()
        trial = 0
        while trial < min_trials or time.perf_counter() - start < max_seconds:
            rng = np.random.RandomState(trial + 11000)
            n = rng.randint(20, 60)
            n_groups = rng.randint(2, 8)
            group_labels = rng.randint(-1, n_groups, size=n).astype(np.int32)

            X = rng.randn(n, 3)
            mcs = rng.choice([2, 3, 5])
            method = rng.choice(["eom", "leaf"])

            labels, _ = fast_hdbscan(
                X, min_cluster_size=mcs, min_samples=2,
                algorithm="kruskal", knn_k=None,
                cannot_link_groups=group_labels,
                cluster_selection_method=method,
            )

            # Check no CL violations
            cl_pairs = _groups_to_cl_pairs(group_labels)
            v = _check_cl_violations(labels, cl_pairs)
            assert len(v) == 0, (
                f"CL violation at trial {trial} (n={n}, n_groups={n_groups}, "
                f"mcs={mcs}, {method}, seed={trial + 11000}): {v}"
            )
            trial += 1

        elapsed = time.perf_counter() - start
        print(f"\n  group CL stress: {trial} trials in {elapsed:.2f}s")


class TestCannotLinkGroupsLargeGroups:
    """Tests with >64 groups requiring multi-word bitmask."""

    @pytest.mark.parametrize("n_groups", [65, 128, 200])
    def test_large_groups_no_violations(self, n_groups):
        """Verify n_groups={n_groups} groups work with multi-word bitmask."""
        rng = np.random.RandomState(n_groups)
        # At least 2 samples per group to have actual constraints
        n = n_groups * 2
        # Assign each pair of samples to a distinct group
        group_labels = np.repeat(np.arange(n_groups, dtype=np.int32), 2)
        # Shuffle to mix positions
        perm = rng.permutation(n)
        group_labels = group_labels[perm]

        X = rng.randn(n, 3)

        labels, _ = fast_hdbscan(
            X, min_cluster_size=3, min_samples=2,
            algorithm="kruskal", knn_k=None,
            cannot_link_groups=group_labels,
        )

        cl_pairs = _groups_to_cl_pairs(group_labels)
        v = _check_cl_violations(labels, cl_pairs)
        assert len(v) == 0, (
            f"CL violation with {n_groups} groups: {v[:5]}..."
        )

    def test_65_groups_core(self):
        """Verify _kruskal_core_group_constrained works with 65 groups (2 words)."""
        # Build a small graph where conflict is across the 64-bit boundary
        n = 5
        weights = np.array([1.0, 2.0, 3.0, 4.0], dtype=np.float64)
        row_idx = np.array([0, 1, 2, 3], dtype=np.int32)
        col_idx = np.array([1, 2, 3, 4], dtype=np.int32)
        so = np.argsort(weights, kind="stable").astype(np.int32)

        # Node 0 in group 0, node 4 in group 64 (second word) — no conflict
        # Node 0 in group 0, node 2 in group 0 — conflict
        group_labels = np.array([0, -1, 0, -1, 64], dtype=np.int32)
        n_groups = 65

        mst_edges, preds = _kruskal_core_group_constrained(
            weights, row_idx, col_idx, so, n, group_labels, n_groups,
        )
        labels = _get_component_labels_jit(preds)
        # 0 and 2 are in group 0, so they must be separated
        assert labels[0] != labels[2], "Group-0 members must be separated"
        # 0 and 4 are in different groups (0 vs 64), so merge is allowed
        # if path connects them without violating constraints

    def test_128_groups_core_equivalence(self):
        """128 groups: verify group-label CL matches sparse-matrix CL."""
        from fast_hdbscan.kruskal import (
            _kruskal_core_constrained, _validate_cannot_link,
        )

        rng = np.random.RandomState(128)
        n_groups = 128
        n = 30
        # Assign random groups (some may be unused)
        group_labels = rng.randint(0, n_groups, size=n).astype(np.int32)

        cl_mat = _groups_to_cl_matrix(group_labels)
        cl_i, cl_p = _validate_cannot_link(cl_mat, n)

        tri_r, tri_c = np.triu_indices(n, k=1)
        weights = rng.uniform(0.1, 5.0, size=len(tri_r)).astype(np.float64)
        tri_r = tri_r.astype(np.int32)
        tri_c = tri_c.astype(np.int32)
        so = np.argsort(weights, kind="stable").astype(np.int32)

        mst_sparse, _ = _kruskal_core_constrained(
            weights, tri_r, tri_c, so, n, cl_i, cl_p
        )
        actual_n_groups = int(group_labels.max()) + 1
        mst_group, _ = _kruskal_core_group_constrained(
            weights, tri_r, tri_c, so, n, group_labels, actual_n_groups,
        )

        np.testing.assert_array_equal(
            mst_sparse, mst_group,
            err_msg="128-group MST edges differ from sparse CL equivalent",
        )
