"""
Tests for Kruskal MST implementation and parity against Borůvka.

Coverage:
  - Correctness on a small graph with known MST
  - Exact MST-weight parity between Kruskal and Borůvka on precomputed graphs
  - HDBSCAN cluster-label parity (Kruskal vs Borůvka) on feature matrices
  - Disconnected and edge-case graphs (isolated nodes, single edge, etc.)
  - HDBSCAN API: algorithm='kruskal' with both metric='euclidean' and
    metric='precomputed'
  - compute_minimum_spanning_tree bad-algorithm guard
  
Tested generated by Claude Sonnet and Opus 4.6. Manual review and editing by Richard Hakim 2026_03_05.
"""

import numpy as np
import pytest
from scipy import sparse
from scipy.spatial import distance
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler
from sklearn.utils import shuffle

from fast_hdbscan import HDBSCAN, fast_hdbscan
from fast_hdbscan.hdbscan import compute_minimum_spanning_tree


# ---------------------------------------------------------------------------
# Shared helpers / datasets
# ---------------------------------------------------------------------------

def _make_connected_sparse_graph(n=12, seed=7):
    """Chain + random extra edges — always connected."""
    rng = np.random.RandomState(seed)
    rows, cols, data = [], [], []
    for i in range(n - 1):
        w = rng.uniform(0.1, 1.0)
        rows += [i, i + 1]
        cols += [i + 1, i]
        data += [w, w]
    for _ in range(n):
        i, j = rng.choice(n, 2, replace=False)
        w = rng.uniform(0.1, 2.0)
        rows += [i, j]
        cols += [j, i]
        data += [w, w]
    return sparse.csr_matrix((data, (rows, cols)), shape=(n, n), dtype=np.float64)


def _full_pairwise_sparse(X):
    """Complete pairwise Euclidean distance CSR from float32-cast feature matrix."""
    X32 = X.astype(np.float32)
    D = distance.cdist(X32, X32)
    np.fill_diagonal(D, 0.0)
    return sparse.csr_matrix(D)


def _align_labels(ref, other):
    mapping = {}
    for r, o in zip(ref, other):
        if r == -1 or o == -1:
            continue
        mapping.setdefault(o, []).append(r)
    remap = {o: max(set(vs), key=vs.count) for o, vs in mapping.items()}
    return np.array([remap.get(v, v) for v in other])


# Module-level datasets (computed once)
_X_blobs, _ = make_blobs(
    n_samples=60,
    centers=[[-4, -4], [0, 0], [4, 4]],
    cluster_std=0.3,
    random_state=0,
)
_X_blobs = StandardScaler().fit_transform(_X_blobs)

from sklearn import datasets as _sk_datasets
_X_moons, _ = _sk_datasets.make_moons(n_samples=100, noise=0.05, random_state=0)
_X_moons = StandardScaler().fit_transform(_X_moons)

_G_blobs = _full_pairwise_sparse(_X_blobs)
_G_moons = _full_pairwise_sparse(_X_moons)


# ---------------------------------------------------------------------------
# 1. Kruskal JIT correctness on a tiny known graph
# ---------------------------------------------------------------------------

def test_kruskal_known_triangle():
    """
    3-node complete graph.  Edges: 0-1 w=1, 1-2 w=2, 0-2 w=3.
    MST must contain 0-1 (w=1) and 1-2 (w=2).  Total weight = 3.
    """
    rows = [0, 1, 1, 2, 0, 2]
    cols = [1, 0, 2, 1, 2, 0]
    data = [1.0, 1.0, 2.0, 2.0, 3.0, 3.0]
    G = sparse.csr_matrix((data, (rows, cols)), shape=(3, 3), dtype=np.float64)

    mst, _, core_dists = compute_minimum_spanning_tree(
        G, min_samples=1, metric="precomputed", algorithm="kruskal"
    )
    assert mst.shape == (2, 3), "MST must have n-1=2 edges"
    assert np.isclose(np.sort(mst[:, 2]).sum(), 3.0), "Total MST weight must equal 3"


def test_kruskal_known_line_graph():
    """
    4-node path  0-1-2-3 with weights 4, 1, 3.
    MST == the path itself (no cycles).  min_samples=1 → cd=0 → MRD=edge weight.
    """
    rows = [0, 1, 1, 2, 2, 3]
    cols = [1, 0, 2, 1, 3, 2]
    data = [4.0, 4.0, 1.0, 1.0, 3.0, 3.0]
    G = sparse.csr_matrix((data, (rows, cols)), shape=(4, 4), dtype=np.float64)

    mst, _, _ = compute_minimum_spanning_tree(
        G, min_samples=1, metric="precomputed", algorithm="kruskal"
    )
    assert mst.shape == (3, 3)
    assert np.isclose(np.sort(mst[:, 2]).sum(), 1 + 3 + 4)


# ---------------------------------------------------------------------------
# 2. MST edge-count invariant
# ---------------------------------------------------------------------------

def test_kruskal_precomputed_edge_count():
    G = _make_connected_sparse_graph(n=15, seed=99)
    mst, neighbors, core_dists = compute_minimum_spanning_tree(
        G, min_samples=3, metric="precomputed", algorithm="kruskal"
    )
    assert mst.shape == (14, 3), "MST must have n-1=14 edges for n=15"
    assert neighbors.shape[0] == 15
    assert core_dists.shape == (15,)


def test_kruskal_feature_matrix_edge_count():
    mst, neighbors, core_dists = compute_minimum_spanning_tree(
        _X_blobs, min_samples=5, metric="euclidean", algorithm="kruskal",
        knn_k=10,
    )
    n = _X_blobs.shape[0]
    assert mst.shape == (n - 1, 3), f"Expected {n - 1} MST edges, got {mst.shape[0]}"
    assert neighbors.shape[0] == n
    assert core_dists.shape == (n,)


# ---------------------------------------------------------------------------
# 3. Kruskal vs Borůvka MST weight parity on precomputed sparse graphs
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("min_samples", [1, 3, 5])
def test_kruskal_boruvka_precomputed_mst_weights(min_samples):
    """
    Kruskal and Borůvka, given the same precomputed graph, must produce
    identical MST edge-weight multisets.

    Kruskal works entirely in float64; Borůvka uses float32 internally but
    patches weights back to float64 afterwards.  On a full pairwise distance
    graph (no float32 precision gap) the resulting sorted weights must be
    bit-for-bit equal.
    """
    G = _G_blobs

    mst_k, _, cd_k = compute_minimum_spanning_tree(
        G, min_samples=min_samples, metric="precomputed", algorithm="kruskal"
    )
    mst_b, _, cd_b = compute_minimum_spanning_tree(
        G, min_samples=min_samples, metric="precomputed", algorithm="boruvka"
    )

    assert mst_k.shape == mst_b.shape, "MST sizes must match"
    np.testing.assert_array_equal(
        np.sort(mst_k[:, 2]),
        np.sort(mst_b[:, 2]),
        err_msg=(
            f"Kruskal vs Borůvka sorted MST weights differ "
            f"(min_samples={min_samples})"
        ),
    )
    np.testing.assert_array_equal(cd_k, cd_b, err_msg="Core distances must match")


# ---------------------------------------------------------------------------
# 4. Disconnected and degenerate graphs
# ---------------------------------------------------------------------------

def test_kruskal_disconnected_two_components():
    """Two isolated cliques → exactly one +inf bridge edge."""
    rows = [0, 1, 1, 2, 3, 4]
    cols = [1, 0, 2, 1, 4, 3]
    data = [1.0] * 6
    G = sparse.csr_matrix((data, (rows, cols)), shape=(5, 5), dtype=np.float64)

    mst, _, _ = compute_minimum_spanning_tree(
        G, min_samples=1, metric="precomputed", algorithm="kruskal"
    )
    assert mst.shape == (4, 3), "MST must have n-1=4 edges"
    inf_count = int(np.sum(np.isinf(mst[:, 2])))
    assert inf_count == 1, f"Expected 1 inf bridge edge, got {inf_count}"


def test_kruskal_fully_isolated_nodes():
    """Empty graph: all n-1 MST edges must be +inf bridges."""
    n = 6
    G = sparse.csr_matrix((n, n), dtype=np.float64)
    mst, _, _ = compute_minimum_spanning_tree(
        G, min_samples=1, metric="precomputed", algorithm="kruskal"
    )
    assert mst.shape == (n - 1, 3)
    assert np.all(np.isinf(mst[:, 2])), "All bridge edges must be +inf"


def test_kruskal_two_nodes():
    """Minimal graph: 2 nodes, 1 edge."""
    G = sparse.csr_matrix(
        ([1.5, 1.5], ([0, 1], [1, 0])), shape=(2, 2), dtype=np.float64
    )
    mst, _, _ = compute_minimum_spanning_tree(
        G, min_samples=1, metric="precomputed", algorithm="kruskal"
    )
    assert mst.shape == (1, 3)
    assert np.isclose(mst[0, 2], 1.5)


# ---------------------------------------------------------------------------
# 5. HDBSCAN cluster-label parity: Kruskal == Borůvka
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("dataset,X,G", [
    ("blobs", _X_blobs, _G_blobs),
    ("moons", _X_moons, _G_moons),
])
@pytest.mark.parametrize("min_samples", [1, 5])
def test_hdbscan_kruskal_boruvka_precomputed_label_parity(dataset, X, G, min_samples):
    """
    HDBSCAN with algorithm='kruskal' on precomputed graph must yield the same
    cluster assignments as algorithm='boruvka'.
    """
    k = HDBSCAN(
        min_cluster_size=10, min_samples=min_samples,
        metric="precomputed", algorithm="kruskal",
    ).fit(G)
    b = HDBSCAN(
        min_cluster_size=10, min_samples=min_samples,
        metric="precomputed", algorithm="boruvka",
    ).fit(G)

    k_n = len(set(k.labels_) - {-1})
    b_n = len(set(b.labels_) - {-1})
    assert k_n == b_n, (
        f"[{dataset} ms={min_samples}] cluster count: kruskal={k_n} boruvka={b_n}"
    )

    aligned = _align_labels(b.labels_, k.labels_)
    assert np.array_equal(b.labels_, aligned), (
        f"[{dataset} ms={min_samples}] label mismatch after alignment"
    )


@pytest.mark.parametrize("dataset,X", [
    ("blobs", _X_blobs),
    ("moons", _X_moons),
])
@pytest.mark.parametrize("min_samples", [1, 5])
def test_hdbscan_kruskal_boruvka_euclidean_label_parity(dataset, X, min_samples):
    """
    HDBSCAN with algorithm='kruskal' on feature matrix must yield the same
    cluster count as algorithm='boruvka'.  (Exact label equality is not
    guaranteed because Kruskal on KNN graph is an approximation of the full
    Borůvka MST, but for well-separated data they agree.)
    """
    k = HDBSCAN(
        min_cluster_size=10, min_samples=min_samples, algorithm="kruskal",
        knn_k=10,
    ).fit(X)
    b = HDBSCAN(
        min_cluster_size=10, min_samples=min_samples, algorithm="boruvka",
    ).fit(X)

    k_n = len(set(k.labels_) - {-1})
    b_n = len(set(b.labels_) - {-1})
    assert k_n == b_n, (
        f"[{dataset} ms={min_samples}] cluster count: kruskal={k_n} boruvka={b_n}"
    )


# ---------------------------------------------------------------------------
# 6. fast_hdbscan() function API with algorithm kwarg
# ---------------------------------------------------------------------------

def test_fast_hdbscan_kruskal_euclidean():
    labels, probs = fast_hdbscan(_X_blobs, min_cluster_size=10, algorithm="kruskal", knn_k=10)
    assert labels.shape == (_X_blobs.shape[0],)
    assert len(set(labels) - {-1}) >= 1


def test_fast_hdbscan_kruskal_precomputed():
    labels, probs = fast_hdbscan(
        _G_blobs, min_cluster_size=10, metric="precomputed", algorithm="kruskal"
    )
    assert labels.shape == (_G_blobs.shape[0],)
    n_clusters = len(set(labels) - {-1})
    assert n_clusters >= 1


# ---------------------------------------------------------------------------
# 7. Bad algorithm raises ValueError
# ---------------------------------------------------------------------------

def test_bad_algorithm_raises():
    with pytest.raises(ValueError, match="algorithm"):
        compute_minimum_spanning_tree(_X_blobs, algorithm="invalid_algo")


# ---------------------------------------------------------------------------
# 8. MST is a valid spanning tree (no self-loops, correct vertex range)
# ---------------------------------------------------------------------------

def _is_valid_spanning_tree(mst, n):
    """Check connectivity of non-inf MST edges using union-find."""
    finite = mst[~np.isinf(mst[:, 2])]
    # All vertex indices in range
    if len(finite) > 0:
        assert finite[:, :2].min() >= 0
        assert finite[:, :2].max() < n
    # No self-loops
    assert np.all(finite[:, 0] != finite[:, 1])


def test_kruskal_valid_spanning_tree_precomputed():
    G = _make_connected_sparse_graph(n=20, seed=42)
    mst, _, _ = compute_minimum_spanning_tree(
        G, min_samples=3, metric="precomputed", algorithm="kruskal"
    )
    _is_valid_spanning_tree(mst, 20)


def test_kruskal_valid_spanning_tree_euclidean():
    mst, _, _ = compute_minimum_spanning_tree(
        _X_blobs, min_samples=5, metric="euclidean", algorithm="kruskal",
        knn_k=10,
    )
    _is_valid_spanning_tree(mst, _X_blobs.shape[0])


# ---------------------------------------------------------------------------
# 9. Kruskal precomputed: explicit zero edges and asymmetric symmetrization
# ---------------------------------------------------------------------------

def test_kruskal_explicit_zero_edge_preserved():
    """Zero-weight edge must survive symmetrization and appear in MST."""
    rows = [0, 1, 1, 2, 2, 3]
    cols = [1, 0, 2, 1, 3, 2]
    data = [0.0, 0.0, 1.0, 1.0, 1.0, 1.0]
    G = sparse.csr_matrix((data, (rows, cols)), shape=(4, 4), dtype=np.float64)

    mst, _, _ = compute_minimum_spanning_tree(
        G, min_samples=1, metric="precomputed", algorithm="kruskal"
    )
    assert mst.shape == (3, 3)
    assert np.any(mst[:, 2] == 0.0), "Zero-weight edge must be in MST"


def test_kruskal_asymmetric_min_symmetrization():
    """Asymmetric weights symmetrized by min: edge (0,1) uses min(5,1)=1."""
    rows = [0, 1, 1, 2]
    cols = [1, 0, 2, 1]
    data = [5.0, 1.0, 2.0, 2.0]
    G = sparse.csr_matrix((data, (rows, cols)), shape=(3, 3), dtype=np.float64)

    mst, _, _ = compute_minimum_spanning_tree(
        G, min_samples=1, metric="precomputed", algorithm="kruskal"
    )
    edge_01 = mst[
        ((mst[:, 0] == 0) & (mst[:, 1] == 1))
        | ((mst[:, 0] == 1) & (mst[:, 1] == 0))
    ]
    assert len(edge_01) == 1
    assert np.isclose(edge_01[0, 2], 1.0), "Symmetrized edge weight must be 1.0"


# ---------------------------------------------------------------------------
# 10. Kruskal min_samples=1 (zero core distances) on feature matrix
# ---------------------------------------------------------------------------

def test_kruskal_feature_matrix_min_samples_1():
    mst, neighbors, core_dists = compute_minimum_spanning_tree(
        _X_blobs, min_samples=1, metric="euclidean", algorithm="kruskal",
        knn_k=10,
    )
    n = _X_blobs.shape[0]
    assert mst.shape == (n - 1, 3)
    assert np.all(core_dists == 0.0), "min_samples=1 -> zero core distances"


# ---------------------------------------------------------------------------
# 11. knn_k parameter: brute-force (knn_k=None) vs KNN (knn_k=int)
# ---------------------------------------------------------------------------

def test_kruskal_brute_edge_count():
    """knn_k=None (full pairwise) must produce exactly n-1 MST edges."""
    mst, neighbors, core_dists = compute_minimum_spanning_tree(
        _X_blobs, min_samples=5, metric="euclidean", algorithm="kruskal",
        knn_k=None,
    )
    n = _X_blobs.shape[0]
    assert mst.shape == (n - 1, 3)
    assert not np.any(np.isinf(mst[:, 2])), "Brute-force MST should have no inf edges"


def test_kruskal_brute_min_samples_1():
    """knn_k=None with min_samples=1 -> zero core distances, valid MST."""
    mst, neighbors, core_dists = compute_minimum_spanning_tree(
        _X_blobs, min_samples=1, metric="euclidean", algorithm="kruskal",
        knn_k=None,
    )
    n = _X_blobs.shape[0]
    assert mst.shape == (n - 1, 3)
    assert np.all(core_dists == 0.0)


@pytest.mark.parametrize("min_samples", [1, 5])
def test_kruskal_brute_vs_boruvka_mst_weights(min_samples):
    """
    Brute-force Kruskal (exact MST) and Boruvka (also exact) on the same
    feature data must produce identical sorted MST weight multisets.

    Small precision differences are possible because Boruvka works in
    float32 rdist internally while brute Kruskal uses cdist float64.
    We check approximate equality with tight tolerance.
    """
    mst_k, _, cd_k = compute_minimum_spanning_tree(
        _X_blobs, min_samples=min_samples, metric="euclidean",
        algorithm="kruskal", knn_k=None,
    )
    mst_b, _, cd_b = compute_minimum_spanning_tree(
        _X_blobs, min_samples=min_samples, metric="euclidean",
        algorithm="boruvka",
    )
    assert mst_k.shape == mst_b.shape
    np.testing.assert_allclose(
        np.sort(mst_k[:, 2]),
        np.sort(mst_b[:, 2]),
        rtol=1e-5,
        err_msg=f"Brute Kruskal vs Boruvka MST weights differ (ms={min_samples})",
    )


def test_kruskal_knn_explicit_k():
    """knn_k=<int> must produce valid MST with n-1 edges."""
    mst, neighbors, core_dists = compute_minimum_spanning_tree(
        _X_blobs, min_samples=5, metric="euclidean", algorithm="kruskal",
        knn_k=15,
    )
    n = _X_blobs.shape[0]
    assert mst.shape == (n - 1, 3)
    assert neighbors.shape[0] == n
    assert core_dists.shape == (n,)


def test_kruskal_knn_k_less_than_min_samples():
    """knn_k < min_samples should still work (k_query = max(knn_k, min_samples) + 1)."""
    mst, neighbors, core_dists = compute_minimum_spanning_tree(
        _X_blobs, min_samples=10, metric="euclidean", algorithm="kruskal",
        knn_k=3,
    )
    n = _X_blobs.shape[0]
    assert mst.shape == (n - 1, 3)


@pytest.mark.parametrize("min_samples", [1, 5])
def test_hdbscan_kruskal_brute_label_parity(min_samples):
    """HDBSCAN with knn_k=None (brute Kruskal) vs Boruvka on blobs."""
    k = HDBSCAN(
        min_cluster_size=10, min_samples=min_samples,
        algorithm="kruskal", knn_k=None,
    ).fit(_X_blobs)
    b = HDBSCAN(
        min_cluster_size=10, min_samples=min_samples,
        algorithm="boruvka",
    ).fit(_X_blobs)

    k_n = len(set(k.labels_) - {-1})
    b_n = len(set(b.labels_) - {-1})
    assert k_n == b_n, f"cluster count: kruskal_brute={k_n} boruvka={b_n}"


def test_hdbscan_kruskal_knn_k_explicit():
    """HDBSCAN with explicit knn_k threads through correctly."""
    h = HDBSCAN(
        min_cluster_size=10, min_samples=5, algorithm="kruskal", knn_k=20,
    ).fit(_X_blobs)
    assert h.labels_.shape == (_X_blobs.shape[0],)
    assert len(set(h.labels_) - {-1}) >= 1


def test_fast_hdbscan_knn_k_param():
    """fast_hdbscan() accepts knn_k parameter."""
    labels, probs = fast_hdbscan(
        _X_blobs, min_cluster_size=10, algorithm="kruskal", knn_k=15,
    )
    assert labels.shape == (_X_blobs.shape[0],)
    assert len(set(labels) - {-1}) >= 1
